-- ============================================================================
-- BTC MT5 → BingX Scalper — Initial Database Schema
-- PostgreSQL 15+
-- ============================================================================
-- This database is ASYNC ONLY — never in the critical order path.
-- All writes are buffered and flushed by the async log writer.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Signals: every signal generated by MT5
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS signals (
    id              BIGSERIAL       PRIMARY KEY,
    signal_id       TEXT            UNIQUE NOT NULL,
    strategy_id     TEXT            NOT NULL,
    symbol          TEXT            NOT NULL,
    side            TEXT            NOT NULL CHECK (side IN ('BUY', 'SELL')),
    signal_price    NUMERIC(18,8),
    bid             NUMERIC(18,8),
    ask             NUMERIC(18,8),
    spread          NUMERIC(18,8),
    features_json   JSONB,
    status          TEXT            NOT NULL,
    t0_tick_ms      BIGINT,
    t1_signal_ms    BIGINT,
    t2_bridge_ms    BIGINT,
    t3_server_ms    BIGINT,
    created_at      TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_signals_signal_id ON signals (signal_id);
CREATE INDEX idx_signals_created_at ON signals (created_at);
CREATE INDEX idx_signals_status ON signals (status);

-- ---------------------------------------------------------------------------
-- Orders: every order sent to BingX
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id                  BIGSERIAL       PRIMARY KEY,
    signal_id           TEXT            NOT NULL,
    client_order_id     TEXT            UNIQUE NOT NULL,
    exchange_order_id   TEXT,
    symbol              TEXT            NOT NULL,
    side                TEXT            NOT NULL CHECK (side IN ('BUY', 'SELL')),
    role                TEXT            NOT NULL CHECK (role IN ('entry', 'exit', 'emergency')),
    order_type          TEXT            NOT NULL,
    time_in_force       TEXT,
    limit_price         NUMERIC(18,8),
    qty                 NUMERIC(18,8),
    status              TEXT            NOT NULL,
    avg_fill_price      NUMERIC(18,8),
    filled_qty          NUMERIC(18,8),
    reduce_only         BOOLEAN         DEFAULT FALSE,
    fee                 NUMERIC(18,8),
    fee_asset           TEXT,
    t4_send_ms          BIGINT,
    t5_ack_ms           BIGINT,
    t6_fill_ms          BIGINT,
    created_at          TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_orders_signal_id ON orders (signal_id);
CREATE INDEX idx_orders_client_order_id ON orders (client_order_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_created_at ON orders (created_at);

-- ---------------------------------------------------------------------------
-- Fills: individual fill events (partial or full)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fills (
    id                  BIGSERIAL       PRIMARY KEY,
    client_order_id     TEXT            NOT NULL,
    exchange_order_id   TEXT,
    fill_price          NUMERIC(18,8)   NOT NULL,
    fill_qty            NUMERIC(18,8)   NOT NULL,
    fee                 NUMERIC(18,8),
    fee_asset           TEXT,
    is_maker            BOOLEAN,
    fill_time_ms        BIGINT,
    created_at          TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_fills_client_order_id ON fills (client_order_id);

-- ---------------------------------------------------------------------------
-- Positions: position lifecycle
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS positions (
    id              BIGSERIAL       PRIMARY KEY,
    position_id     TEXT            UNIQUE NOT NULL,
    signal_id       TEXT            NOT NULL,
    symbol          TEXT            NOT NULL,
    side            TEXT            NOT NULL CHECK (side IN ('LONG', 'SHORT')),
    entry_price     NUMERIC(18,8),
    exit_price      NUMERIC(18,8),
    qty             NUMERIC(18,8),
    realized_pnl    NUMERIC(18,8),
    gross_pnl       NUMERIC(18,8),
    total_fees      NUMERIC(18,8),
    status          TEXT            NOT NULL,
    entry_reason    TEXT,
    exit_reason     TEXT,
    trailing_step   INT             DEFAULT 0,
    entry_time_ms   BIGINT,
    exit_time_ms    BIGINT,
    holding_ms      BIGINT,
    entry_slippage  NUMERIC(18,8),
    exit_slippage   NUMERIC(18,8),
    created_at      TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_positions_signal_id ON positions (signal_id);
CREATE INDEX idx_positions_status ON positions (status);
CREATE INDEX idx_positions_created_at ON positions (created_at);

-- ---------------------------------------------------------------------------
-- Latency logs: T0-T7 timestamps for every signal/order
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS latency_logs (
    id                  BIGSERIAL       PRIMARY KEY,
    signal_id           TEXT            NOT NULL,
    client_order_id     TEXT,
    t0_tick_ms          BIGINT,
    t1_signal_ms        BIGINT,
    t2_bridge_recv_ms   BIGINT,
    t3_server_recv_ms   BIGINT,
    t4_order_send_ms    BIGINT,
    t5_ack_ms           BIGINT,
    t6_fill_ms          BIGINT,
    t7_closed_ms        BIGINT,
    mt5_to_bridge_ms    NUMERIC(12,3),
    bridge_to_server_ms NUMERIC(12,3),
    server_prep_ms      NUMERIC(12,3),
    api_ack_ms          NUMERIC(12,3),
    signal_to_ack_ms    NUMERIC(12,3),
    signal_to_fill_ms   NUMERIC(12,3),
    holding_ms          NUMERIC(12,3),
    created_at          TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_latency_signal_id ON latency_logs (signal_id);
CREATE INDEX idx_latency_created_at ON latency_logs (created_at);

-- ---------------------------------------------------------------------------
-- Risk state: daily risk counters (one row per trading day)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS risk_state (
    trade_date              DATE        PRIMARY KEY,
    daily_trade_count       INT         DEFAULT 0,
    daily_stop_loss_count   INT         DEFAULT 0,
    consecutive_losses      INT         DEFAULT 0,
    current_risk_percent    NUMERIC(6,3) DEFAULT 1.0,
    trading_enabled         BOOLEAN     DEFAULT TRUE,
    kill_switch_active      BOOLEAN     DEFAULT FALSE,
    kill_switch_reason      TEXT,
    updated_at              TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Errors: all errors and anomalies
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS errors (
    id          BIGSERIAL       PRIMARY KEY,
    signal_id   TEXT,
    order_id    TEXT,
    error_type  TEXT            NOT NULL,
    error_msg   TEXT            NOT NULL,
    severity    TEXT            NOT NULL CHECK (severity IN ('INFO', 'WARN', 'ERROR', 'FATAL')),
    context     JSONB,
    created_at  TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_errors_created_at ON errors (created_at);
CREATE INDEX idx_errors_error_type ON errors (error_type);

-- ---------------------------------------------------------------------------
-- System events: startup, shutdown, config changes, kill switch, etc.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_events (
    id          BIGSERIAL       PRIMARY KEY,
    event_type  TEXT            NOT NULL,
    event_data  JSONB,
    created_at  TIMESTAMPTZ     DEFAULT now()
);

CREATE INDEX idx_system_events_type ON system_events (event_type);
CREATE INDEX idx_system_events_created_at ON system_events (created_at);

COMMIT;
